### PR TITLE
Add basic authentication

### PR DESCRIPTION
**Pull request by justinkrol**
This creates a new model, `AuthenticatedUser`, as the system will seed the `user` and `professor` tables with existing data.
In a follow-up PR, we will connect an `AuthenticatedUser` to a student or prof record.

----------------
## 1
image

----------------
## 2
image

----------------
## 3
image

----------------
## 4
image
----------------

### CODE REVIEW

**Comment by DerekStride** [comment]
logging in, logging out, and registration seems to work. I get the occasional error in the spring logs but it doesn't render anything in the browser.

**Comment by justinkrol** [comment]
Errors are now rendering. Updated OP

**Review by JFleming4 — COMMENTED** [review]
Should the page redirect you after creating an account? Or should this be a seperate issue

**Review by JFleming4 — APPROVED** [review]
It looks good, The errors are being displayed, It is denying access. When we log in we should redirect the, to their specific page i.e. I'm a student when I log in/create account I should be taken to the student page. On account creation it kinda just leaves you at a page that says you have logged in in plain text with the option to log out.

**Comment by justinkrol** [comment]
I think it's a separate issue. We need to make the student page take a student id anyway, so I'm doing it in [this PR](https://github.com/JFleming4/FourthYearProjectSite/pull/48), which connects student/professor records to authentication accounts

**Pull request merged**
