### PR TITLE
File uploads for proposal and final report

### LINKED ISSUE #34: Setup a local storage bucket API for local development and testing

### PR DESCRIPTION
**Pull request by DerekStride**
closes #34, #13

This PR adds the necessary classes to upload files to a remote bucket. It does so by introducing the `StorageService` interface.

In local development the `FileSystemStorageService` Bean is instantiated and used by the `FileController` it will write and read files from a local folder on your machine.

In production the `CloudStorageService` Bean is configured to read/write to Amazon S3.

### CODE REVIEW

**Review by JFleming4 — COMMENTED** [review]
Do we require tests for FileAttachment.java? and FileController.java?

**Review by JFleming4 — APPROVED** [review]
👀 👍  🐑 🇮🇹  🚢 🇮🇹  :shipit:

**Comment by justinkrol** [comment]
He ask for bigger PRs, he shall receive!

**Review by justinkrol — APPROVED** [review]
Good looking PR ✨

**Pull request merged**
